name: witchcraft-cybersecurity
version: "0.36.10"
summary: witchcraft - A versatile toolkit for cybersecurity.
grade: stable
confinement: strict
base: core24
type: app
compression: lzo
license: GPL-3.0+
source-code: https://github.com/cosmic-zip/witchcraft

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

environment:
  WITCH_SPELLS_ROOT_DIR: $SNAP/archive/

parts:
  witchspells:
    source: spellbook
    plugin: dump

  witchcraft:
    after: [witchspells]
    plugin: rust
    source: ./witchcraft
    stage-packages:
      - chromium
      - nmap
      - whois
      - dirb
      - dnsenum
      - libc-bin
      - iproute2
      - xxd
      - iptables
      - coreutils
      - wget
      - curl
      - dnsutils
      - traceroute
      - openssl
      - openssh-server
      - xattr
      - libimage-exiftool-perl
      - tor
      - foremost
      - pkg-config
      - steghide
      - file
      - 7zip
      - libssl-dev
      - libwebkit2gtk-4.1-dev
      - libxdo-dev
      - libglu1-mesa
      - build-essential
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libclang-dev
      - liboss4-salsa-asound2
      - freeglut3-dev
      - libllvm15
      - libatomic1
      - libclang1-18
      - libatm1t64
      - git

    build-packages:
      - clang
      - gcc

apps:
  witchcraft:
    command: bin/witchcraft
    plugs: [home, network, network-bind, removable-media]
